apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpoc-deployment
  namespace: atomic-pocs
  labels:
    app: cpoc
spec:
  selector:
    matchLabels:
      app: cpoc
  replicas: 1
  template:
    metadata:
      name: cpoc-pod
      labels:
        app: cpoc
    spec:
      containers:
      - name: cpoc
        image: docker.pkg.github.com/atomicpocs/cpoc/cpoc:1.0.0
        ports:
        - name: http 
          containerPort: 4567
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        livenessProbe:
            httpGet:
              path: /ping
              port: 4567
            initialDelaySeconds: 5
            periodSeconds: 5
      imagePullSecrets:
        - name: regcred
